-- gen_font.lua
--
-- Turns the hardware's bitmap font into lib/ui/font.lua.
--
-- The source is teletype/libavr32/src/font.c -- Henrik Theiling's Liquid
-- font, adapted for aleph by monome in 2012 and used by every Teletype
-- screen. It is 96 glyphs of 6x8, stored column-first, with a per-glyph
-- inset from each side so the spacing is proportional rather than fixed.
--
-- Transcribing 96 glyphs by hand is 576 hex bytes of opportunity for a typo,
-- and a wrong bit is a wrong pixel that nobody notices until they compare
-- against hardware. Generated instead.
--
-- usage: lua5.4 lib/ui/tools/gen_font.lua

local IN = '../teletype/libavr32/src/font.c'
local OUT = 'lib/ui/font.lua'

-- font.h: the glyph box is 6 wide by 8 tall, and the table starts at space
local CHARW = 6
local ASCII_OFFSET = 0x20

local src = assert(io.open(IN)):read('a')

-- the table runs from its opening brace to the first `};`
local body = src:match('const glyph_t font_data%[%]%s*=%s*(.-)\n};')
assert(body, 'could not find font_data in ' .. IN)

-- each live entry is `{ /* comment */ first, last, { c0, ..., c5 } },`.
-- The commented-out duplicate uppercase I is skipped by requiring the line to
-- start with `{` -- font.c leaves the serif-less version in as `//`.
local glyphs = {}
for line in body:gmatch('[^\n]+') do
  if line:match('^%s*{') then
    local first, last, data =
      line:match('{%s*/%*.-%*/%s*(%d+)%s*,%s*(%d+)%s*,%s*{([^}]*)}')
    if first then
      local cols = {}
      for byte in data:gmatch('0x%x+') do cols[#cols + 1] = tonumber(byte) end
      assert(#cols == CHARW,
        ('glyph %d has %d columns, expected %d'):format(#glyphs, #cols, CHARW))
      glyphs[#glyphs + 1] = {
        first = tonumber(first), last = tonumber(last), cols = cols,
      }
    end
  end
end

-- 0x20 through 0x7e. font.c also carries a commented-out serif-less uppercase
-- I; the `^%s*{` match above drops it, and this count is what catches it if a
-- future edit uncomments it and shifts every glyph after 0x49.
assert(#glyphs == 95, ('expected 95 glyphs, parsed %d'):format(#glyphs))

local out = {}
local function emit(s) out[#out + 1] = s end

emit('-- lib/ui/font.lua -- generated by lib/ui/tools/gen_font.lua')
emit('--')
emit('-- The Teletype system font, from teletype/libavr32/src/font.c. Do not')
emit('-- edit: run `make generated` instead.')
emit('--')
emit('-- One entry per printable ASCII character, from 0x20. `first` and')
emit('-- `last` are the blank columns inset from each side of the 6-wide box,')
emit('-- so a glyph draws columns first..(6-last-1) and advances by')
emit('-- (6 - first - last) + 1 -- the +1 being the single blank column')
emit('-- font_string puts between characters.')
emit('--')
emit('-- `cols` is column-first: pixel(x, y) is set when cols[x] has bit y,')
emit('-- counting y down from the top of the 8-row cell.')
emit('')
emit(('local M = { CHARW = %d, CHARH = 8, ASCII_OFFSET = 0x%02x }')
  :format(CHARW, ASCII_OFFSET))
emit('')
emit('M.glyphs = {')

for i, g in ipairs(glyphs) do
  local ch = string.char(ASCII_OFFSET + i - 1)
  local hex = {}
  for _, c in ipairs(g.cols) do hex[#hex + 1] = ('0x%02x'):format(c) end
  -- the comment is the character itself, so a diff of this file is readable
  emit(('  { %d, %d, { %s } },   -- %s'):format(
    g.first, g.last, table.concat(hex, ', '),
    ch == ' ' and 'space' or ch))
end

emit('}')
emit('')
emit('return M')

local f = assert(io.open(OUT, 'w'))
f:write(table.concat(out, '\n'))
f:write('\n')
f:close()

print(('wrote %s (%d glyphs)'):format(OUT, #glyphs))
